# Generated by Django 4.2 on 2023-12-07 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('benches', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='benchimage',
            name='image',
            field=models.ImageField(upload_to='bench/None', verbose_name='Дополнительное фото'),
        ),
    ]
