# Generated by Django 4.2 on 2023-12-07 12:24

import benches.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('benches', '0003_alter_benchimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bench',
            name='avatar',
            field=models.ImageField(blank=True, default='default.png', null=True, upload_to='bench_avatars/'),
        ),
        migrations.AlterField(
            model_name='bench',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='benches.benchdistrict'),
        ),
        migrations.AlterField(
            model_name='bench',
            name='environment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='benches.benchenvironment'),
        ),
        migrations.AlterField(
            model_name='bench',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='benches.benchtype'),
        ),
        migrations.AlterField(
            model_name='benchimage',
            name='image',
            field=models.ImageField(upload_to=benches.models.BenchImage.image_upload_to, verbose_name='Дополнительное фото'),
        ),
    ]
