# Generated by Django 4.2 on 2023-12-07 12:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import userSystem.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('benches', '0004_alter_bench_avatar_alter_bench_district_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bench',
            name='author',
            field=models.ForeignKey(default=userSystem.models.CustomUser, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
    ]
