# Generated by Django 4.2 on 2023-12-07 12:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import userSystem.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('benches', '0005_alter_bench_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bench',
            name='author',
            field=models.ForeignKey(default=userSystem.models.CustomUser, editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='bench',
            name='rating',
            field=models.FloatField(default=0.0),
        ),
    ]
