# Generated by Django 4.2 on 2023-12-07 12:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('benches', '0006_alter_bench_author_alter_bench_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bench',
            name='rating',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)]),
        ),
    ]
